<?php
global $cfg_Cs;
$cfg_Cs=array();
$cfg_Cs[1]=array(0,1,1,'QWJvdXQg5oiR5Lus');
$cfg_Cs[2]=array(0,1,1,'U2VydmljZXMg5pyN5Yqh');
$cfg_Cs[3]=array(0,1,1,'TmV3cyDliqjmgIE=');
$cfg_Cs[4]=array(0,2,1,'V29ya3Mg5qGI5L6L');
$cfg_Cs[6]=array(4,2,1,'QnJhbmQgZGVzaWduIOWTgeeJjOiuvuiuoQ==');
$cfg_Cs[7]=array(4,2,1,'QWN0aXZpdHkg5YWs5YWz5rS75Yqo');
$cfg_Cs[8]=array(4,2,1,'UHJpbnRpbmcg5Y2w5Yi3fOWItuS9nA==');
$cfg_Cs[9]=array(4,2,1,'T3RoZXIg5YW25a6D');
$cfg_Cs[10]=array(0,1,1,'Q29udGFjdCDogZTns7s=');
$cfg_Cs[11]=array(0,1,1,'SG9tZSDpppbpobU=');
$cfg_Cs[12]=array(2,1,1,'5ZOB54mM6K6+6K6h');
$cfg_Cs[13]=array(2,1,1,'5YWs5YWz5rS75Yqo');
$cfg_Cs[14]=array(2,1,1,'5Y2w5Yi3fOWItuS9nA==');
$cfg_Cs[15]=array(2,1,1,'56m66Ze05a+86KeG');
?>