<div class="member-photo">
                <div class="bw-wrapper"><a href="[field:arcurl/]"><img src="[field:litpic /]" alt="[field:fulltitle/]"></a></div>
              </div>
              <div class="member-info">
                <h4>Other</h4>
                <span class="position">其它-空间导视</span>
                <p>空间导视、标牌标识设计制作.</p>
                <ul class="member-social-links">
                  <li><a href="[field:arcurl/]">任务:其它-空间导视</a></li>
                </ul>
              </div>