<div class="post clearfix"> <a href="[field:arcurl/]">
                  <h5>[field:title/]</h5>
                  </a>
                  <ul class="post-meta">
                    <li class="author">By：<a href="[field:arcurl/]">[field:pubdate function=strftime('%Y-%m-%d %H:%M',@me)/]</a></li>
                  </ul>
                  <div class="post-entry"> <a href="[field:arcurl/]" title="[field:fulltitle/]"><img src="[field:litpic/]" alt="[field:fulltitle/]" class="image"></a>
                    <p>[field:description function='cn_substr(@me,210)'/]...<a href="[field:arcurl/]">Read more...</a></p>
                  </div>
                </div>