<?php
$z[0]=Array("arcurl","",37,52);
$z[1]=Array("title","",78,92);
$z[2]=Array("arcurl","",218,233);
$z[3]=Array("pubdate","",235,291);
$z[3][4]['function']="strftime('%Y-%m-%d";
$z[3][4]['%H:%M,@me)']="";
$z[4]=Array("arcurl","",379,394);
$z[5]=Array("fulltitle","",403,421);
$z[6]=Array("litpic","",433,448);
$z[7]=Array("fulltitle","",455,473);
$z[8]=Array("description","",518,568);
$z[8][4]['function']="cn_substr(@me,210)";
$z[9]=Array("arcurl","",580,595);

?>