<div class="one-fourth project-item branddesign"> <img src="[field:litpic /]" alt="[field:fulltitle/]">
                  <div class="overlay"> <a href="[field:litpic /]" class="lightbox-link folio" rel="gallery"></a> <a href="[field:arcurl/]">
                    <h5>Brand design</h5>
                    </a>
                    <p>[field:title/]</p>
                  </div>
                </div>