<div class="member-photo">
                <div class="bw-wrapper"><a href="[field:arcurl/]"><img src="[field:litpic /]" alt="[field:fulltitle/]"></a></div>
              </div>
              <div class="member-info">
                <h4>Activity</h4>
                <span class="position">公关活动</span>
                <p>会议公关活动策划+执行！</p>
                <ul class="member-social-links">
                  <li><a href="[field:arcurl/]">任务:公关活动</a></li>
                </ul>
              </div>