<div class="member-photo">
                <div class="bw-wrapper"><a href="[field:arcurl/]"><img src="[field:litpic /]" alt="[field:fulltitle/]"></a></div>
              </div>
              <div class="member-info">
                <h4>Brand design</h4>
                <span class="position">品牌设计-包装设计</span>
                <p>包装设计,产品市场定位。</p>
                <ul class="member-social-links">
                  <li><a href="[field:arcurl/]">任务:品牌设计-包装设计</a></li>
                </ul>
              </div>