<?php
$z[0]=Array("arclist","\r\n              <li><a href=\"[field:arcurl/]\">\r\n                <div class=\"bw-wrapper\"><img src=\"[field:litpic /]\" alt=\"[field:fulltitle/]\" width=\"186px\" height=\"89px\"></div>\r\n                </a></li>\r\n              ",626,909);
$z[0][4]['row']="5";
$z[0][4]['orderby']="id";
$z[0][4]['typeid']="4";
$z[1]=Array("global","",1339,1371);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("sql","[field:content function=cn_substr(Html2Text(@me),180)/]...",1438,1567);
$z[2][4]['sql']="select content from dede_arctype where id=1";
$z[3]=Array("arclist","\r\n                <p>[field:title/]<a href=\"[field:arcurl/]\"> View....</a> <span class=\"tweet-time\">[field:pubdate function=strftime('%Y-%m-%d %H:%M',@me)/]</span> </p>\r\n                ",1788,2040);
$z[3][4]['row']="3";
$z[3][4]['orderby']="id";
$z[3][4]['typeid']="3";
$z[4]=Array("global","",2345,2366);
$z[4][4]['name']="cfg_dz";
$z[5]=Array("global","",2425,2447);
$z[5][4]['name']="cfg_tel";
$z[6]=Array("global","",2475,2496);
$z[6][4]['name']="cfg_dh";
$z[7]=Array("global","",2539,2560);
$z[7][4]['name']="cfg_yx";
$z[8]=Array("arclist","\r\n                <li><a href=\"[field:arcurl/]\"><img src=\"[field:litpic /]\" alt=\"[field:fulltitle/]\"></a></li>\r\n                ",2805,2984);
$z[8][4]['row']="8";
$z[8][4]['typeid']="4";
$z[9]=Array("global","",3283,3309);
$z[9][4]['name']="cfg_powerby";
$z[10]=Array("global","",3311,3335);
$z[10][4]['name']="cfg_beian";
$z[11]=Array("global","",4260,4292);
$z[11][4]['name']="cfg_templets_skin";

?>