<?php
$z[0]=Array("global","",235,267);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("global","",302,328);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("channelartlist","\r\n            <li> <a href=\"{dede:field name='typeurl'/}\">{dede:field name='typename'/}</a> \r\n              <!--                  <ul>\r\n				{dede:channel type='son'}\r\n                    <li><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n				{/dede:channel} \r\n                </ul>	 --> \r\n            </li>\r\n            ",424,828);
$z[2][4]['row']="8";
$z[2][4]['typeid']="1,2,3,4,10,11";

?>