// JavaScript Documentdocument.writeln("<!doctype html>");
document.writeln("<html lang=\"en\">");
document.writeln("<head>");
document.writeln("<meta charset=\"utf-8\">");
document.writeln("<style>");
document.writeln("#pagewrap {");
document.writeln("        background: #fff;");
document.writeln("        left: 50%;");
document.writeln("        margin-left: -520px;");
document.writeln("        position: relative;");
document.writeln("        width: 1040px;");
document.writeln("}");
document.writeln("");
document.writeln("/*");
document.writeln("Back to top button ");
document.writeln("*/");
document.writeln("#back-qq {");
document.writeln("	position: fixed;");
document.writeln("	bottom: 30px;");
document.writeln("	left: 30px;");
document.writeln("}");
document.writeln("#back-qq a {");
document.writeln("	width: 108px;");
document.writeln("	display: block;");
document.writeln("	text-align: center;");
document.writeln("	font: 11px/100% Arial, Helvetica, sans-serif;");
document.writeln("	text-transform: uppercase;");
document.writeln("	text-decoration: none;");
document.writeln("	color: #bbb;");
document.writeln("	/* background color transition */");
document.writeln("	-webkit-transition: 1s;");
document.writeln("	-moz-transition: 1s;");
document.writeln("	transition: 1s;");
document.writeln("}");
document.writeln("#back-qq a:hover {");
document.writeln("	color: #000;");
document.writeln("}");
document.writeln("/* arrow icon (span tag) */");
document.writeln("#back-qq span {");
document.writeln("	width: 108px;");
document.writeln("	height: 108px;");
document.writeln("	display: block;");
document.writeln("	margin-bottom: 7px;");
document.writeln("	background: #ddd url(/templets/muban/images/up-arrow.png) no-repeat center center;");
document.writeln("	/* rounded corners */");
document.writeln("	-webkit-border-radius: 5px;");
document.writeln("	-moz-border-radius: 5px;");
document.writeln("	border-radius: 5px;");
document.writeln("	/* background color transition */");
document.writeln("	-webkit-transition: 1s;");
document.writeln("	-moz-transition: 1s;");
document.writeln("	transition: 1s;");
document.writeln("}");
document.writeln("#back-qq a:hover span {");
document.writeln("	background-color: #777;");
document.writeln("}");
document.writeln("</style>");
document.writeln("");
document.writeln("</head>");
document.writeln("");
document.writeln("<body id=\"qq\">");
document.writeln("<div id=\"pagewrap\">");
document.writeln("	<p id=\"back-qq\">");
document.writeln("		<a href=\"http://wpa.qq.com/msgrd?v=3&uin=789843055&site=qq&menu=yes\" target=\"_blank\"><span></span>QQ online</a>");
document.writeln("	</p>");
document.writeln("");
document.writeln("</div>");
document.writeln("</body>");
document.writeln("</html>");